spring.application.name=la-fabrica-burger-backend
server.servlet.context-path=/api/v1
server.port=8088
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=la_fabrica_burger;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
security.jwt.secret=Ristorino2024SecretKeyDAS12345!!
